/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

// The delay settings for an automation email.
type AutomationDelay1 struct {
	// The delay amount for an automation email.
	Amount int32 `json:"amount,omitempty"`
	// The type of delay for an automation email.
	Type_ string `json:"type,omitempty"`
	// Whether the delay settings describe before or after the delay action of an automation email.
	Direction string `json:"direction,omitempty"`
	// The action that triggers the delay of an automation emails.
	Action string `json:"action"`
}
