/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

// Configure a webhook for the given list.
type AddWebhook struct {
	// A valid URL for the Webhook.
	Url string `json:"url,omitempty"`
	Events *Events1 `json:"events,omitempty"`
	Sources *Sources `json:"sources,omitempty"`
}
