/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

// The clicks and visits data from the last seven days.
type DailyClicksAndVisitsData struct {
	Clicks []DailyClicksAndVisitsDataClicks `json:"clicks,omitempty"`
	Visits []DailyClicksAndVisitsDataVisits `json:"visits,omitempty"`
	UniqueVisits []DailyClicksAndVisitsDataUniqueVisits `json:"unique_visits,omitempty"`
}
