/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

import (
	"time"
)

// A specific note for a specific member.
type MemberNotes struct {
	// The note id.
	Id int32 `json:"id,omitempty"`
	// The date and time the note was created in ISO 8601 format.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// The author of the note.
	CreatedBy string `json:"created_by,omitempty"`
	// The date and time the note was last updated in ISO 8601 format.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// The content of the note.
	Note string `json:"note,omitempty"`
	// The unique id for the list.
	ListId string `json:"list_id,omitempty"`
	// The MD5 hash of the lowercase version of the list member's email address.
	EmailId string `json:"email_id,omitempty"`
	// As Mailchimp evolves beyond email, you may eventually have contacts without email addresses. While the `email_id` is the MD5 hash of their email address, this `contact_id` is agnostic of contact’s inclusion of an email address.
	ContactId string `json:"contact_id,omitempty"`
	// A list of link types and descriptions for the API schema documents.
	Links []ResourceLink `json:"_links,omitempty"`
}
