/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

type AbTestOptionsCombinations struct {
	// Unique ID for the combination.
	Id string `json:"id,omitempty"`
	// The index of `variate_settings.subject_lines` used.
	SubjectLine int32 `json:"subject_line,omitempty"`
	// The index of `variate_settings.send_times` used.
	SendTime int32 `json:"send_time,omitempty"`
	// The index of `variate_settings.from_names` used.
	FromName int32 `json:"from_name,omitempty"`
	// The index of `variate_settings.reply_to_addresses` used.
	ReplyTo int32 `json:"reply_to,omitempty"`
	// The index of `variate_settings.contents` used.
	ContentDescription int32 `json:"content_description,omitempty"`
	// The number of recipients for this combination.
	Recipients int32 `json:"recipients,omitempty"`
}
