/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

import (
	"time"
)

// An object describing the open activity for the campaign.
type Opens struct {
	// The total number of opens for a campaign.
	OpensTotal int32 `json:"opens_total,omitempty"`
	// The total number of unique opens.
	UniqueOpens int32 `json:"unique_opens,omitempty"`
	// The number of unique opens divided by the total number of successful deliveries.
	OpenRate float32 `json:"open_rate,omitempty"`
	// The date and time of the last recorded open in ISO 8601 format.
	LastOpen time.Time `json:"last_open,omitempty"`
}
