/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

// Connected Site
type InlineResponse2009Site struct {
	// The ID of this connected site.
	Id int32 `json:"id,omitempty"`
	// The name of the connected site
	Name string `json:"name,omitempty"`
	// The URL for this connected site.
	Url string `json:"url,omitempty"`
}
