/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

// abandonedCart automation details.
type AbandonedCartAutomation struct {
	// Whether this store supports the abandonedCart automation.
	IsSupported bool `json:"is_supported,omitempty"`
	// Unique ID of automation parent campaign.
	Id string `json:"id,omitempty"`
	// Status of the abandonedCart automation.
	Status string `json:"status,omitempty"`
}
