/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

// Information about a specific connected site.
type ConnectedSite1 struct {
	// The unique identifier for the site.
	ForeignId string `json:"foreign_id"`
	// The connected site domain.
	Domain string `json:"domain"`
}
