/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

// An object describing the forwards and forward activity for the campaign.
type Forwards struct {
	// How many times the campaign has been forwarded.
	ForwardsCount int32 `json:"forwards_count,omitempty"`
	// How many times the forwarded campaign has been opened.
	ForwardsOpens int32 `json:"forwards_opens,omitempty"`
}
