/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

// A list of abuse complaints for a specific list.
type AbuseComplaints1 struct {
	// An array of objects, each representing an abuse report resource.
	AbuseReports []AbuseComplaint1 `json:"abuse_reports,omitempty"`
	// The campaign id.
	CampaignId string `json:"campaign_id,omitempty"`
	// The total number of items matching the query regardless of pagination.
	TotalItems int32 `json:"total_items,omitempty"`
	// A list of link types and descriptions for the API schema documents.
	Links []ResourceLink `json:"_links,omitempty"`
}
