/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

// An object describing campaign engagement on Facebook.
type FacebookLikes struct {
	// The number of recipients who liked the campaign on Facebook.
	RecipientLikes int32 `json:"recipient_likes,omitempty"`
	// The number of unique likes.
	UniqueLikes int32 `json:"unique_likes,omitempty"`
	// The number of Facebook likes for the campaign.
	FacebookLikes int32 `json:"facebook_likes,omitempty"`
}
