/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

// A [merge field](https://mailchimp.com/developer/marketing/docs/merge-fields/) for an audience.
type MergeField3 struct {
	// An unchanging id for the merge field.
	Id int32 `json:"id,omitempty"`
	// The [label](https://mailchimp.com/developer/marketing/docs/merge-fields/#structure) for the merge field.
	Label string `json:"label,omitempty"`
	// The [type](https://mailchimp.com/developer/marketing/docs/merge-fields/#structure) for the merge field.
	Type_ string `json:"type,omitempty"`
}
