/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

// The delay settings for an Automation email.
type AutomationDelay struct {
	// The delay amount for an Automation email.
	Amount int32 `json:"amount,omitempty"`
	// The type of delay for an Automation email.
	Type_ string `json:"type,omitempty"`
	// Whether the delay settings describe before or after the delay action of an Automation email.
	Direction string `json:"direction,omitempty"`
	// The action that triggers the delay of an Automation email.
	Action string `json:"action,omitempty"`
	// The user-friendly description of the action that triggers an Automation email.
	ActionDescription string `json:"action_description,omitempty"`
	// The user-friendly description of the delay and trigger action settings for an Automation email.
	FullDescription string `json:"full_description,omitempty"`
}
