/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

// A collection of a product's variants.
type EcommerceProductVariants struct {
	// The store id.
	StoreId string `json:"store_id,omitempty"`
	// The product id.
	ProductId string `json:"product_id,omitempty"`
	// An array of objects, each representing a product's variants.
	Variants []EcommerceProductVariant `json:"variants,omitempty"`
	// The total number of items matching the query regardless of pagination.
	TotalItems int32 `json:"total_items,omitempty"`
	// A list of link types and descriptions for the API schema documents.
	Links []ResourceLink `json:"_links,omitempty"`
}
