/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

// A summary of a subscriber removed from an Automation workflow.
type SubscriberRemovedFromAutomationWorkflow struct {
	// The MD5 hash of the lowercase version of the list member's email address.
	Id string `json:"id,omitempty"`
	// A string that uniquely identifies an Automation workflow.
	WorkflowId string `json:"workflow_id,omitempty"`
	// A string that uniquely identifies a list.
	ListId string `json:"list_id,omitempty"`
	// The list member's email address.
	EmailAddress string `json:"email_address,omitempty"`
	// A list of link types and descriptions for the API schema documents.
	Links []ResourceLink `json:"_links,omitempty"`
}
