/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

// A collection of an order's line items.
type OrderLines struct {
	// The store id.
	StoreId string `json:"store_id,omitempty"`
	// The order id.
	OrderId string `json:"order_id,omitempty"`
	// An array of objects, each representing an order's line item.
	Lines []EcommerceOrderLineItem `json:"lines,omitempty"`
	// The total number of items matching the query regardless of pagination.
	TotalItems int32 `json:"total_items,omitempty"`
	// A list of link types and descriptions for the API schema documents.
	Links []ResourceLink `json:"_links,omitempty"`
}
