/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

// The verified domains currently on the account.
type VerifiedDomains2 struct {
	// The e-mail address at the domain you want to verify. This will receive a two-factor challenge to be used in the verify action.
	VerificationEmail string `json:"verification_email"`
}
