/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

// A list of reports containing child campaigns for a specific campaign.
type CampaignSubReports struct {
	// An array of objects, each representing a report resource.
	Reports []CampaignReport `json:"reports,omitempty"`
	// Unique identifier of the parent campaign
	CampaignId string `json:"campaign_id,omitempty"`
	// The total number of items matching the query regardless of pagination.
	TotalItems int32 `json:"total_items,omitempty"`
	// A list of link types and descriptions for the API schema documents.
	Links []ResourceLink `json:"_links,omitempty"`
}
