/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

type BatchUpdateListMembersTags struct {
	// The tag id.
	Id int32 `json:"id,omitempty"`
	// The name of the tag
	Name string `json:"name,omitempty"`
}
