/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

// A summary of social activity for the campaign, tracked by EepURL.
type EepurlActivity struct {
	Twitter *TwitterStats `json:"twitter,omitempty"`
	Clicks *ClickSummary `json:"clicks,omitempty"`
	// A summary of the top referrers for the campaign.
	Referrers []Referrer `json:"referrers,omitempty"`
	// The shortened link used for tracking.
	Eepurl string `json:"eepurl,omitempty"`
	// The unique id for the campaign.
	CampaignId string `json:"campaign_id,omitempty"`
	// The total number of items matching the query regardless of pagination.
	TotalItems int32 `json:"total_items,omitempty"`
	// A list of link types and descriptions for the API schema documents.
	Links []ResourceLink `json:"_links,omitempty"`
}
