/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

// Details about an individual conversation. Conversation tracking is a feature available to paid accounts that lets you view replies to your campaigns in your Mailchimp account.
type Conversation struct {
	// A string that uniquely identifies this conversation.
	Id string `json:"id,omitempty"`
	// The total number of messages in this conversation.
	MessageCount int32 `json:"message_count,omitempty"`
	// The unique identifier of the campaign for this conversation.
	CampaignId string `json:"campaign_id,omitempty"`
	// The unique identifier of the list for this conversation.
	ListId string `json:"list_id,omitempty"`
	// The number of unread messages in this conversation.
	UnreadMessages int32 `json:"unread_messages,omitempty"`
	// A label representing the sender of this message.
	FromLabel string `json:"from_label,omitempty"`
	// A label representing the email of the sender of this message.
	FromEmail string `json:"from_email,omitempty"`
	// The subject of the message.
	Subject string `json:"subject,omitempty"`
	LastMessage *LastMessage `json:"last_message,omitempty"`
	// A list of link types and descriptions for the API schema documents.
	Links []ResourceLink `json:"_links,omitempty"`
}
