/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

// Information about a specific cart line item.
type EcommerceCartLineItem struct {
	// A unique identifier for the cart line item.
	Id string `json:"id,omitempty"`
	// A unique identifier for the product associated with the cart line item.
	ProductId string `json:"product_id,omitempty"`
	// The name of the product for the cart line item.
	ProductTitle string `json:"product_title,omitempty"`
	// A unique identifier for the product variant associated with the cart line item.
	ProductVariantId string `json:"product_variant_id,omitempty"`
	// The name of the product variant for the cart line item.
	ProductVariantTitle string `json:"product_variant_title,omitempty"`
	// The quantity of a cart line item.
	Quantity int32 `json:"quantity,omitempty"`
	// The price of a cart line item.
	Price float32 `json:"price,omitempty"`
	// A list of link types and descriptions for the API schema documents.
	Links []ResourceLink `json:"_links,omitempty"`
}
