/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

import (
	"time"
)

type InlineResponse20011 struct {
	// A list of link types and descriptions for the API schema documents.
	Links []ResourceLink `json:"_links,omitempty"`
	Audience *InlineResponse2009Audience `json:"audience,omitempty"`
	AudienceActivity *InlineResponse20011AudienceActivity `json:"audience_activity,omitempty"`
	Budget *InlineResponse2009Budget `json:"budget,omitempty"`
	// The date and time the outreach was canceled in ISO 8601 format.
	CanceledAt time.Time `json:"canceled_at,omitempty"`
	Channel *InlineResponse2009Channel `json:"channel,omitempty"`
	// The date and time the outreach was created in ISO 8601 format.
	CreateTime time.Time `json:"create_time,omitempty"`
	EmailSourceName string `json:"email_source_name,omitempty"`
	// The date and time the ad was ended in ISO 8601 format.
	EndTime time.Time `json:"end_time,omitempty"`
	// If this outreach targets a segment of your audience.
	HasSegment bool `json:"has_segment,omitempty"`
	// Unique ID of an Outreach.
	Id string `json:"id,omitempty"`
	// Title or name of an Outreach.
	Name string `json:"name,omitempty"`
	// If the ad has a problem and needs attention.
	NeedsAttention bool `json:"needs_attention,omitempty"`
	// The date and time the ad was paused in ISO 8601 format.
	PausedAt time.Time `json:"paused_at,omitempty"`
	// The date and time the outreach was (or will be) published in ISO 8601 format.
	PublishedTime time.Time `json:"published_time,omitempty"`
	Recipients *Recipients `json:"recipients,omitempty"`
	ReportSummary *InlineResponse20011ReportSummary `json:"report_summary,omitempty"`
	// Outreach report availability. Note: This property is hotly debated in what it _should_ convey. See [MCP-1371](https://jira.mailchimp.com/browse/MCP-1371) for more context.
	ShowReport bool `json:"show_report,omitempty"`
	// The date and time the outreach was started in ISO 8601 format.
	StartTime time.Time `json:"start_time,omitempty"`
	// The status of this outreach.
	Status string `json:"status,omitempty"`
	// The URL of the thumbnail for this outreach.
	Thumbnail string `json:"thumbnail,omitempty"`
	// The type of outreach this object is.
	Type_ string `json:"type,omitempty"`
	// The date and time the outreach was last updated in ISO 8601 format.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	WasCanceledByFacebook bool `json:"was_canceled_by_facebook,omitempty"`
	// The ID used in the Mailchimp web application. For example, for a `regular` outreach, you can view this campaign in your Mailchimp account at `https://{dc}.admin.mailchimp.com/campaigns/show/?id={web_id}`.
	WebId int32 `json:"web_id,omitempty"`
}
