/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

type InlineResponse2009AudienceTargetingSpecsLocations struct {
	Countries []string `json:"countries,omitempty"`
	Regions []string `json:"regions,omitempty"`
	Cities []string `json:"cities,omitempty"`
	Zips []string `json:"zips,omitempty"`
}
