/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

type Body2 struct {
	// An array of email addresses to send the test email to.
	TestEmails []string `json:"test_emails"`
	// Choose the type of test email to send.
	SendType string `json:"send_type"`
}
