/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

// The [average campaign statistics](https://mailchimp.com/resources/research/email-marketing-benchmarks/?utm_source=mc-api&utm_medium=docs&utm_campaign=apidocs) for all campaigns in the account's specified industry.
type IndustryStats struct {
	// The average unique open rate for all campaigns in the account's specified industry.
	OpenRate float32 `json:"open_rate,omitempty"`
	// The average bounce rate for all campaigns in the account's specified industry.
	BounceRate float32 `json:"bounce_rate,omitempty"`
	// The average unique click rate for all campaigns in the account's specified industry.
	ClickRate float32 `json:"click_rate,omitempty"`
}
