/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

import (
	"time"
)

// The report for a survey.
type SurveyReport struct {
	// A string that uniquely identifies this survey.
	Id string `json:"id,omitempty"`
	// The ID used in the Mailchimp web application. View this survey report in your Mailchimp account at `https://{dc}.admin.mailchimp.com/lists/surveys/results?survey_id={web_id}`.
	WebId int32 `json:"web_id,omitempty"`
	// The ID of the list connected to this survey.
	ListId string `json:"list_id,omitempty"`
	// The name of the list connected to this survey.
	ListName string `json:"list_name,omitempty"`
	// The title of the survey.
	Title string `json:"title,omitempty"`
	// The URL for the survey.
	Url string `json:"url,omitempty"`
	// The survey's status.
	Status string `json:"status,omitempty"`
	// The date and time the survey was published in ISO 8601 format.
	PublishedAt time.Time `json:"published_at,omitempty"`
	// The date and time the survey was created in ISO 8601 format.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// The date and time the survey was last updated in ISO 8601 format.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// The total number of responses to this survey.
	TotalResponses int32 `json:"total_responses,omitempty"`
}
