/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

// An individual click location.
type Location3 struct {
	// The two-digit country code for a recorded click.
	Country string `json:"country,omitempty"`
	// If available, a specific region where the click was recorded.
	Region string `json:"region,omitempty"`
}
