/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

// Information about subscribers in an Automation email queue.
type SubscriberInAutomationQueue1 struct {
	// The list member's email address.
	EmailAddress string `json:"email_address"`
}
