/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

// Update an existing Batch Webook.
type BatchWebhook2 struct {
	// A valid URL for the Webhook.
	Url string `json:"url,omitempty"`
	// Whether the webhook receives requests or not.
	Enabled bool `json:"enabled,omitempty"`
}
