/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

import (
	"time"
)

// The most recent Note added about this member.
type Notes struct {
	// The note id.
	NoteId int32 `json:"note_id,omitempty"`
	// The date and time the note was created in ISO 8601 format.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// The author of the note.
	CreatedBy string `json:"created_by,omitempty"`
	// The content of the note.
	Note string `json:"note,omitempty"`
}
