/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

// Stats for Group A.
type GroupA struct {
	// The total number of clicks for Group A.
	TotalClicksA int32 `json:"total_clicks_a,omitempty"`
	// The percentage of total clicks for Group A.
	ClickPercentageA float32 `json:"click_percentage_a,omitempty"`
	// The number of unique clicks for Group A.
	UniqueClicksA int32 `json:"unique_clicks_a,omitempty"`
	// The percentage of unique clicks for Group A.
	UniqueClickPercentageA float32 `json:"unique_click_percentage_a,omitempty"`
}
