/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

// A breakdown of clicks by different groups of an A/B Split campaign. Does not return information about Multivariate Campaigns.
type AbSplit struct {
	A *GroupA `json:"a,omitempty"`
	B *GroupB `json:"b,omitempty"`
}
