/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

// Batch add/remove List members to/from static segment
type BatchAddremoveListMembersTofromStaticSegment struct {
	// An array of objects, each representing a new member that was added to the static segment.
	MembersAdded []ListMembers `json:"members_added,omitempty"`
	// An array of objects, each representing an existing list member that got deleted from the static segment.
	MembersRemoved []ListMembers `json:"members_removed,omitempty"`
	// An array of objects, each representing an array of email addresses that could not be added to the segment or removed and an error message providing more details.
	Errors []BatchAddremoveListMembersTofromStaticSegmentErrors `json:"errors,omitempty"`
	// The total number of items matching the query, irrespective of pagination.
	TotalAdded int32 `json:"total_added,omitempty"`
	// The total number of items matching the query, irrespective of pagination.
	TotalRemoved int32 `json:"total_removed,omitempty"`
	// The total number of items matching the query, irrespective of pagination.
	ErrorCount int32 `json:"error_count,omitempty"`
	// A list of link types and descriptions for the API schema documents.
	Links []ResourceLink `json:"_links,omitempty"`
}
