/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

import (
	"time"
)

// Information about a specific customer.
type EcommerceCustomer struct {
	// A unique identifier for the customer.
	Id string `json:"id,omitempty"`
	// The customer's email address.
	EmailAddress string `json:"email_address,omitempty"`
	// The customer's opt-in status. This value will never overwrite the opt-in status of a pre-existing Mailchimp list member, but will apply to list members that are added through the e-commerce API endpoints. Customers who don't opt in to your Mailchimp list [will be added as `Transactional` members](https://mailchimp.com/developer/marketing/docs/e-commerce/#customers).
	OptInStatus bool `json:"opt_in_status,omitempty"`
	// The customer's company.
	Company string `json:"company,omitempty"`
	// The customer's first name.
	FirstName string `json:"first_name,omitempty"`
	// The customer's last name.
	LastName string `json:"last_name,omitempty"`
	// The customer's total order count.
	OrdersCount int32 `json:"orders_count,omitempty"`
	// The total amount the customer has spent.
	TotalSpent float32 `json:"total_spent,omitempty"`
	Address *Address `json:"address,omitempty"`
	// The date and time the customer was created in ISO 8601 format.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// The date and time the customer was last updated in ISO 8601 format.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// A list of link types and descriptions for the API schema documents.
	Links []ResourceLink `json:"_links,omitempty"`
}
