/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

import (
	"time"
)

// An individual folder listed in the File Manager.
type GalleryFolder struct {
	// The unique id for the folder.
	Id int32 `json:"id,omitempty"`
	// The name of the folder.
	Name string `json:"name,omitempty"`
	// The number of files in the folder.
	FileCount int32 `json:"file_count,omitempty"`
	// The date and time a file was added to the File Manager in ISO 8601 format.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// The username of the profile that created the folder.
	CreatedBy string `json:"created_by,omitempty"`
	// A list of link types and descriptions for the API schema documents.
	Links []ResourceLink `json:"_links,omitempty"`
}
