/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

// The HTML and plain-text content for a campaign
type CampaignContent1 struct {
	// The plain-text portion of the campaign. If left unspecified, we'll generate this automatically.
	PlainText string `json:"plain_text,omitempty"`
	// The raw HTML for the campaign.
	Html string `json:"html,omitempty"`
	// When importing a campaign, the URL where the HTML lives.
	Url string `json:"url,omitempty"`
	Template *TemplateContent `json:"template,omitempty"`
	Archive *UploadArchive `json:"archive,omitempty"`
	// Content options for [Multivariate Campaigns](https://mailchimp.com/help/about-multivariate-campaigns/). Each content option must provide HTML content and may optionally provide plain text. For campaigns not testing content, only one object should be provided.
	VariateContents []CampaignscampaignIdcontentVariateContents `json:"variate_contents,omitempty"`
}
