/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

// Interest categories organize interests, which are used to group subscribers based on their preferences. These correspond to Group Titles the application.
type InterestCategory2 struct {
	// The text description of this category. This field appears on signup forms and is often phrased as a question.
	Title string `json:"title"`
	// The order that the categories are displayed in the list. Lower numbers display first.
	DisplayOrder int32 `json:"display_order,omitempty"`
	// Determines how this category’s interests appear on signup forms.
	Type_ string `json:"type"`
}
