/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

// Details for the automations attached to this store.
type Automations struct {
	AbandonedCart *AbandonedCartAutomation `json:"abandoned_cart,omitempty"`
	AbandonedBrowse *AbandonedBrowseAutomation `json:"abandoned_browse,omitempty"`
}
