/*
 * Mailchimp Marketing API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.0.55
 * Contact: apihelp@mailchimp.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package mailchimp

import (
	"time"
)

// A summary of the interaction with the campaign.
type MemberActivity2 struct {
	// One of the following actions: 'open', 'click', or 'bounce'
	Action string `json:"action,omitempty"`
	// If the action is a 'bounce', the type of bounce received: 'hard', 'soft'.
	Type_ string `json:"type,omitempty"`
	// The date and time recorded for the action in ISO 8601 format.
	Timestamp time.Time `json:"timestamp,omitempty"`
	// If the action is a 'click', the URL on which the member clicked.
	Url string `json:"url,omitempty"`
	// The IP address recorded for the action.
	Ip string `json:"ip,omitempty"`
}
